'use client';

import React from 'react';
import { BevGeniePage, PageSection } from '@/lib/ai/page-specs';
import { COLORS } from '@/lib/constants/colors';
import { Download, Share2, ExternalLink } from 'lucide-react';

interface DynamicPageRendererProps {
  page: BevGeniePage;
  onDownload?: () => void;
  onShare?: () => void;
  onNavigationClick?: (action: string, context?: any) => void;
  compact?: boolean; // For displaying in chat vs full page
}

/**
 * Dynamic Page Renderer
 *
 * Converts BevGenie page specifications (JSON) into rendered React components.
 * Supports 6 page types and 8 section types with consistent styling.
 */
export function DynamicPageRenderer({
  page,
  onDownload,
  onShare,
  onNavigationClick,
  compact = false,
}: DynamicPageRendererProps) {
  return (
    <div className={`dynamic-page-renderer ${compact ? 'compact' : 'full'}`}>
      {/* Header with title and actions */}
      {!compact && (
        <div
          className="page-header border-b p-6 mb-6"
          style={{
            backgroundColor: COLORS.white,
            borderColor: COLORS.mediumGray,
          }}
        >
          <div className="flex items-start justify-between mb-3">
            <div>
              <h1
                className="text-3xl font-bold"
                style={{ color: COLORS.navy }}
              >
                {page.title}
              </h1>
              <p className="mt-2" style={{ color: COLORS.textGray }}>
                {page.description}
              </p>
            </div>
            {(onDownload || onShare) && (
              <div className="flex gap-2">
                {onDownload && (
                  <button
                    onClick={onDownload}
                    className="flex items-center gap-2 px-4 py-2 rounded-lg transition-colors"
                    style={{
                      backgroundColor: COLORS.white,
                      borderColor: COLORS.mediumGray,
                      color: COLORS.navy,
                      border: `1px solid ${COLORS.mediumGray}`,
                    }}
                    title="Download as PDF"
                  >
                    <Download className="w-4 h-4" />
                    <span className="text-sm font-medium hidden sm:inline">Download</span>
                  </button>
                )}
                {onShare && (
                  <button
                    onClick={onShare}
                    className="flex items-center gap-2 px-4 py-2 rounded-lg transition-colors"
                    style={{
                      backgroundColor: COLORS.white,
                      borderColor: COLORS.mediumGray,
                      color: COLORS.navy,
                      border: `1px solid ${COLORS.mediumGray}`,
                    }}
                    title="Share this page"
                  >
                    <Share2 className="w-4 h-4" />
                    <span className="text-sm font-medium hidden sm:inline">Share</span>
                  </button>
                )}
              </div>
            )}
          </div>
          <div className="flex gap-2 mt-4 flex-wrap">
            <span
              className="inline-block px-3 py-1 text-xs font-semibold rounded-full"
              style={{
                backgroundColor: `${COLORS.cyan}22`,
                color: COLORS.cyan,
              }}
            >
              {page.type.replace(/_/g, ' ')}
            </span>
            <span
              className="inline-block px-3 py-1 text-xs font-semibold rounded-full"
              style={{
                backgroundColor: `${COLORS.navy}22`,
                color: COLORS.navy,
              }}
            >
              BevGenie Solution
            </span>
          </div>
        </div>
      )}

      {/* Render sections */}
      <div className={`page-content space-y-8 ${compact ? 'max-w-2xl' : ''}`}>
        {page.sections.map((section, index) => (
          <SectionRenderer
            key={index}
            section={section}
            index={index}
            onNavigationClick={onNavigationClick}
          />
        ))}
      </div>

      {/* Footer in full view */}
      {!compact && (
        <div
          className="page-footer border-t p-6 mt-8 text-center"
          style={{
            backgroundColor: COLORS.lightGray,
            borderColor: COLORS.mediumGray,
          }}
        >
          <p className="text-sm" style={{ color: COLORS.textGray }}>
            Generated by{' '}
            <span className="font-semibold" style={{ color: COLORS.cyan }}>
              BevGenie AI
            </span>
            <br />
            Personalized for your beverage business needs
          </p>
        </div>
      )}
    </div>
  );
}

/**
 * Section Renderer
 * Routes to appropriate section component based on section type
 */
function SectionRenderer({
  section,
  index,
  onNavigationClick,
}: {
  section: PageSection;
  index: number;
  onNavigationClick?: (action: string, context?: any) => void;
}) {
  switch (section.type) {
    case 'hero':
      return <HeroSection section={section} onNavigationClick={onNavigationClick} />;
    case 'feature_grid':
      return <FeatureGridSection section={section} onNavigationClick={onNavigationClick} />;
    case 'testimonial':
      return <TestimonialSection section={section} />;
    case 'comparison_table':
      return <ComparisonTableSection section={section} />;
    case 'cta':
      return <CTASection section={section} onNavigationClick={onNavigationClick} />;
    case 'faq':
      return <FAQSection section={section} />;
    case 'metrics':
      return <MetricsSection section={section} />;
    case 'steps':
      return <StepsSection section={section} onNavigationClick={onNavigationClick} />;
    default:
      return (
        <div className="p-4 bg-red-50 border border-red-200 rounded-lg text-red-800">
          Unknown section type: {(section as any).type}
        </div>
      );
  }
}

/**
 * Hero Section Component
 * Large headline with optional CTA button - Professional B2B SaaS styling
 */
function HeroSection({
  section,
  onNavigationClick,
}: {
  section: any;
  onNavigationClick?: (action: string, context?: any) => void;
}) {
  const handleCtaClick = () => {
    if (onNavigationClick) {
      onNavigationClick(section.ctaButton?.action || 'hero_cta_click', {
        text: section.ctaButton?.text,
        context: section.headline,
      });
    }
  };

  const handleLearnMore = () => {
    if (onNavigationClick) {
      onNavigationClick('learn_more', {
        context: section.headline,
      });
    }
  };

  return (
    <div
      className="hero-section py-16 px-12 rounded-xl"
      style={{
        backgroundColor: `linear-gradient(135deg, ${COLORS.navy}15, ${COLORS.cyan}10)`,
        border: `1px solid ${COLORS.mediumGray}`,
      }}
    >
      <div className="max-w-3xl">
        <h2
          className="text-5xl md:text-6xl font-bold mb-6 leading-tight"
          style={{ color: COLORS.navy }}
        >
          {section.headline}
        </h2>
        {section.subheadline && (
          <p
            className="text-xl md:text-2xl mb-10 leading-relaxed font-medium"
            style={{ color: COLORS.darkGray }}
          >
            {section.subheadline}
          </p>
        )}
        {section.ctaButton && (
          <div className="flex flex-wrap gap-4 mt-8">
            <button
              onClick={handleCtaClick}
              className="px-8 py-4 font-bold rounded-lg transition-all hover:shadow-lg transform hover:scale-105 text-white"
              style={{ backgroundColor: COLORS.cyan }}
            >
              {section.ctaButton.text}
            </button>
            <button
              onClick={handleLearnMore}
              className="px-8 py-4 font-bold rounded-lg transition-all hover:shadow-lg border-2"
              style={{
                borderColor: COLORS.navy,
                color: COLORS.navy,
                backgroundColor: COLORS.white,
              }}
            >
              Learn More
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

/**
 * Feature Grid Section Component
 * Grid of features with icons and descriptions - Professional B2B SaaS styling
 */
function FeatureGridSection({ section }: { section: any }) {
  return (
    <div className="feature-grid-section">
      {section.title && (
        <h3
          className="text-4xl font-bold mb-3"
          style={{ color: COLORS.navy }}
        >
          {section.title}
        </h3>
      )}
      {section.subtitle && (
        <p className="mb-12 text-lg" style={{ color: COLORS.darkGray }}>
          {section.subtitle}
        </p>
      )}

      <div
        className={`grid grid-cols-1 md:grid-cols-${section.columns} gap-8`}
        style={{
          gridTemplateColumns: `repeat(${Math.min(section.columns, 3)}, minmax(0, 1fr))`,
        }}
      >
        {section.features.map((feature: any, idx: number) => (
          <div
            key={idx}
            className="feature-card p-8 rounded-xl hover:shadow-xl transition-all hover:border-cyan-300 hover:translate-y-[-4px] duration-300"
            style={{
              backgroundColor: COLORS.white,
              border: `2px solid ${COLORS.mediumGray}`,
            }}
          >
            {feature.icon && (
              <div
                className="text-5xl mb-4 inline-flex items-center justify-center w-14 h-14 rounded-lg"
                style={{
                  backgroundColor: `${COLORS.cyan}15`,
                }}
              >
                {feature.icon}
              </div>
            )}
            <h4
              className="text-xl font-bold mb-3"
              style={{ color: COLORS.navy }}
            >
              {feature.title}
            </h4>
            <p className="text-base leading-relaxed" style={{ color: COLORS.textGray }}>
              {feature.description}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}

/**
 * Testimonial Section Component
 * Customer quote with attribution
 */
function TestimonialSection({ section }: { section: any }) {
  return (
    <div className="testimonial-section">
      <div
        className="p-8 rounded-lg"
        style={{
          backgroundColor: COLORS.lightGray,
          borderLeft: `4px solid ${COLORS.cyan}`,
        }}
      >
        <div className="flex items-start gap-4">
          {section.image && (
            <img
              src={section.image}
              alt={section.author}
              className="w-16 h-16 rounded-full object-cover flex-shrink-0"
            />
          )}
          <div className="flex-grow">
            <blockquote
              className="text-lg italic mb-4"
              style={{ color: COLORS.darkGray }}
            >
              "{section.quote}"
            </blockquote>
            <div>
              <p
                className="font-semibold"
                style={{ color: COLORS.navy }}
              >
                {section.author}
              </p>
              {section.role && (
                <p className="text-sm" style={{ color: COLORS.textGray }}>
                  {section.role}
                </p>
              )}
              {section.company && (
                <p className="text-sm" style={{ color: COLORS.textGray }}>
                  {section.company}
                </p>
              )}
              {section.metric && (
                <p
                  className="text-sm font-semibold mt-2"
                  style={{ color: COLORS.cyan }}
                >
                  {section.metric}
                </p>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

/**
 * Comparison Table Section Component
 * Feature-by-feature comparison matrix
 */
function ComparisonTableSection({ section }: { section: any }) {
  return (
    <div className="comparison-table-section">
      {section.title && (
        <h3
          className="text-2xl font-bold mb-6"
          style={{ color: COLORS.navy }}
        >
          {section.title}
        </h3>
      )}

      <div className="overflow-x-auto">
        <table className="w-full border-collapse">
          <thead>
            <tr style={{ backgroundColor: COLORS.navy, color: COLORS.white }}>
              {section.headers.map((header: string, idx: number) => (
                <th
                  key={idx}
                  className="px-6 py-4 text-left font-semibold border"
                  style={{ borderColor: COLORS.mediumGray }}
                >
                  {header}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {section.rows.map((row: any, rowIdx: number) => (
              <tr
                key={rowIdx}
                style={{
                  backgroundColor:
                    rowIdx % 2 === 0 ? COLORS.white : COLORS.lightGray,
                }}
              >
                <td
                  className="px-6 py-4 font-semibold border"
                  style={{
                    color: COLORS.navy,
                    borderColor: COLORS.mediumGray,
                  }}
                >
                  {row.feature}
                </td>
                {row.values.map((value: any, colIdx: number) => (
                  <td
                    key={colIdx}
                    className="px-6 py-4 border text-center"
                    style={{
                      color: COLORS.darkGray,
                      borderColor: COLORS.mediumGray,
                    }}
                  >
                    {typeof value === 'boolean' ? (
                      value ? (
                        <span style={{ color: COLORS.cyan, fontWeight: 'bold' }}>
                          ✓
                        </span>
                      ) : (
                        <span style={{ color: COLORS.copper, fontWeight: 'bold' }}>
                          ✗
                        </span>
                      )
                    ) : (
                      value
                    )}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

/**
 * CTA Section Component
 * Call-to-action buttons with various actions - Professional B2B SaaS styling
 */
function CTASection({
  section,
  onNavigationClick,
}: {
  section: any;
  onNavigationClick?: (action: string, context?: any) => void;
}) {
  const handleButtonClick = (button: any) => {
    if (onNavigationClick) {
      onNavigationClick(button.action || 'cta_click', {
        text: button.text,
        context: section.title,
        isPrimary: button.primary,
      });
    }
  };

  return (
    <div
      className="cta-section p-16 rounded-2xl shadow-2xl text-center text-white"
      style={{
        backgroundColor: `linear-gradient(135deg, ${COLORS.navy}, #003d7a)`,
      }}
    >
      <h3 className="text-4xl md:text-5xl font-bold mb-4">{section.title}</h3>
      {section.description && (
        <p className="text-lg mb-12 max-w-2xl mx-auto leading-relaxed" style={{ color: '#d1d5db' }}>
          {section.description}
        </p>
      )}

      <div className="flex flex-wrap gap-4 justify-center mt-10">
        {section.buttons.map((button: any, idx: number) => (
          <button
            key={idx}
            onClick={() => handleButtonClick(button)}
            className={`px-8 py-4 font-bold rounded-lg transition-all hover:shadow-xl transform hover:scale-105 ${
              button.primary ? 'text-navy' : ''
            }`}
            style={{
              backgroundColor: button.primary ? COLORS.cyan : 'transparent',
              border: button.primary ? 'none' : `2px solid ${COLORS.cyan}`,
              color: button.primary ? COLORS.navy : COLORS.cyan,
            }}
          >
            {button.text}
          </button>
        ))}
      </div>
    </div>
  );
}

/**
 * FAQ Section Component
 * Accordion-style frequently asked questions
 */
function FAQSection({ section }: { section: any }) {
  const [expandedIndex, setExpandedIndex] = React.useState<number | null>(null);

  return (
    <div className="faq-section">
      {section.title && (
        <h3
          className="text-2xl font-bold mb-6"
          style={{ color: COLORS.navy }}
        >
          {section.title}
        </h3>
      )}

      <div className="space-y-3">
        {section.items.map((item: any, idx: number) => (
          <div
            key={idx}
            className="rounded-lg overflow-hidden hover:shadow-md transition-shadow"
            style={{
              backgroundColor: COLORS.white,
              border: `1px solid ${COLORS.mediumGray}`,
            }}
          >
            <button
              onClick={() =>
                setExpandedIndex(expandedIndex === idx ? null : idx)
              }
              className="w-full px-6 py-4 text-left font-semibold flex items-center justify-between transition-colors"
              style={{
                backgroundColor: COLORS.lightGray,
                color: COLORS.navy,
              }}
            >
              {item.question}
              <span
                className={`transform transition-transform ${
                  expandedIndex === idx ? 'rotate-180' : ''
                }`}
              >
                ▼
              </span>
            </button>
            {expandedIndex === idx && (
              <div
                className="px-6 py-4 border-t"
                style={{
                  color: COLORS.darkGray,
                  backgroundColor: COLORS.white,
                  borderColor: COLORS.mediumGray,
                }}
              >
                {item.answer}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}

/**
 * Metrics Section Component
 * Display key metrics and statistics - Professional B2B SaaS styling
 */
function MetricsSection({ section }: { section: any }) {
  return (
    <div className="metrics-section">
      {section.title && (
        <h3
          className="text-4xl font-bold mb-12"
          style={{ color: COLORS.navy }}
        >
          {section.title}
        </h3>
      )}

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        {section.metrics.map((metric: any, idx: number) => (
          <div
            key={idx}
            className="metric-card p-10 rounded-xl text-center hover:shadow-xl transition-all hover:translate-y-[-4px] duration-300"
            style={{
              backgroundColor: COLORS.white,
              border: `2px solid ${COLORS.mediumGray}`,
            }}
          >
            <div
              className="text-6xl font-bold mb-4"
              style={{ color: COLORS.cyan }}
            >
              {metric.value}
            </div>
            <p
              className="text-xl font-bold mb-3"
              style={{ color: COLORS.navy }}
            >
              {metric.label}
            </p>
            {metric.description && (
              <p className="text-base leading-relaxed" style={{ color: COLORS.darkGray }}>
                {metric.description}
              </p>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}

/**
 * Steps Section Component
 * Implementation or process steps with timeline
 */
function StepsSection({ section }: { section: any }) {
  return (
    <div className="steps-section">
      {section.title && (
        <h3
          className="text-2xl font-bold mb-2"
          style={{ color: COLORS.navy }}
        >
          {section.title}
        </h3>
      )}
      {section.timeline && (
        <p className="text-lg font-semibold mb-8" style={{ color: COLORS.cyan }}>
          Timeline: {section.timeline}
        </p>
      )}

      <div className="relative">
        {/* Vertical line */}
        <div
          className="absolute left-6 top-0 bottom-0 w-1 hidden md:block"
          style={{ backgroundColor: COLORS.cyan }}
        />

        {/* Steps */}
        <div className="space-y-8">
          {section.steps.map((step: any, idx: number) => (
            <div key={idx} className="flex gap-6">
              <div className="flex-shrink-0">
                <div
                  className="flex items-center justify-center w-12 h-12 rounded-full text-white font-bold text-lg shadow-lg"
                  style={{ backgroundColor: COLORS.navy }}
                >
                  {step.number}
                </div>
              </div>
              <div className="flex-grow pt-2">
                <h4
                  className="text-lg font-semibold mb-2"
                  style={{ color: COLORS.navy }}
                >
                  {step.title}
                </h4>
                <p style={{ color: COLORS.textGray }}>{step.description}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

